# Uncomment the next line to define a global platform for your project
 platform :ios, '12.0'

target "Virtual Tourist" do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Virtual Tourist
    pod 'SwiftyJSON', '~> 4.0'
    pod 'Alamofire', '~> 4.8'


end

post_install do |installer|
 installer.pods_project.targets.each do |target|
     target.build_configurations.each do |config|
         config.build_settings['SWIFT_VERSION'] = '4.2'
     end
 end
end
